### ISSUE TITLE
Parquet GC Crash

### ISSUE THREAD

**Issue by altanozlu** [grafana/tempo#1592]
**Describe the bug**
Almost every two days tempo crashes(mostly when i sleep  :/)

**Environment:**
 - Infrastructure: Ubuntu 22 in GCP
 - Tempo version is 9be0ae54dcf5393677b58aac3266b140289a533e

**Additional Context**
```
level=info ts=2022-07-21T02:46:34.415082428Z caller=compactor.go:150 msg="compacting block" block="&{Version:vParquet BlockID:04d6efdf-5d03-4b2e-ad4f-d6de785862f6 MinID:[0 0 0 0 0 0 0 0 0 19 114 70 138 122 196 128] MaxID:[255 253 55 147 253 121 118 45 44 46 196 196 224 202 84 47] TenantID:single-tenant StartTime:2022-07-21 02:41:10 +0000 UTC EndTime:2022-07-21 02:45:44 +0000 UTC TotalObjects:39445 Size:32469406 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:4 DataEncoding: BloomShardCount:1 FooterSize:19866}"
level=info ts=2022-07-21T02:46:34.415256519Z caller=compactor.go:150 msg="compacting block" block="&{Version:vParquet BlockID:0cbf760a-f00c-4e19-8638-0c222cc33c7d MinID:[0 0 0 0 0 0 0 0 0 0 72 181 216 239 229 74] MaxID:[255 254 125 251 18 105 239 112 254 110 161 216 181 72 240 92] TenantID:single-tenant StartTime:2022-07-21 02:16:09 +0000 UTC EndTime:2022-07-21 02:20:14 +0000 UTC TotalObjects:51495 Size:58062539 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:6 DataEncoding: BloomShardCount:1 FooterSize:29007}"
runtime: marked free object in span 0x7f64cb706368, elemsize=24 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc000410000 alloc unmarked
0xc000410018 alloc unmarked
0xc000410030 alloc unmarked
0xc000410048 alloc unmarked
0xc000410060 alloc unmarked
0xc000410078 alloc marked
0xc000410090 alloc unmarked
0xc0004100a8 alloc unmarked
0xc0004100c0 alloc marked
0xc0004100d8 alloc unmarked
0xc0004100f0 alloc marked
0xc000410108 alloc unmarked
0xc000410120 alloc unmarked
0xc000410138 alloc marked
0xc000410150 free  marked   zombie
0x000000c000410150:  0x502d72656765614a  0x2e342d6e6f687479
0x000000c000410160:  0x0000006e6f302e38
0xc000410168 free  unmarked
0xc000410180 free  unmarked
0xc000410198 free  unmarked
.....LONG OUTPUT....
0xc000411f68 free  unmarked
0xc000411f80 free  unmarked
0xc000411f98 free  unmarked
0xc000411fb0 free  unmarked
0xc000411fc8 free  unmarked
0xc000411fe0 free  unmarked
fatal error: found pointer to free object

goroutine 4067 [running]:
runtime.throw({0x1ffd4d0?, 0xc000410168?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00cc0b728 sp=0xc00cc0b6f8 pc=0x438731
runtime.(*mspan).reportZombies(0x7f64cb706368)
        /usr/local/go/src/runtime/mgcsweep.go:776 +0x2e5 fp=0xc00cc0b7a8 sp=0xc00cc0b728 pc=0x427305
runtime.(*sweepLocked).sweep(0x357bca0?, 0x0)
        /usr/local/go/src/runtime/mgcsweep.go:609 +0x8b2 fp=0xc00cc0b880 sp=0xc00cc0b7a8 pc=0x426d12
runtime.sweepone()
        /usr/local/go/src/runtime/mgcsweep.go:369 +0xf0 fp=0xc00cc0b8d0 sp=0xc00cc0b880 pc=0x426190
runtime.GC()
        /usr/local/go/src/runtime/mgc.go:451 +0x7e fp=0xc00cc0b908 sp=0xc00cc0b8d0 pc=0x41bc3e
github.com/grafana/tempo/tempodb/encoding/vparquet.(*Compactor).Compact(0xc0090ecb00, {0x24e8318, 0xc0000500a0}, {0x24d1360, 0xc00001b360}, {0x24f4540, 0xc0009da830}, 0xc01c74fdc0, {0xc01c74fca0, 0x2, ...})
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/compactor.go:105 +0x7f6 fp=0xc00cc0bb50 sp=0xc00cc0b908 pc=0x1340036
github.com/grafana/tempo/tempodb.(*readerWriter).compact(0xc0009c6840, {0xc01c74fca0?, 0x2, 0x2}, {0xc0003ec013, 0xd})
        /root/tempo/repo/tempo/tempodb/compactor.go:189 +0x889 fp=0xc00cc0bdc8 sp=0xc00cc0bb50 pc=0x1794ca9
github.com/grafana/tempo/tempodb.(*readerWriter).doCompaction(0xc0009c6840)
        /root/tempo/repo/tempo/tempodb/compactor.go:113 +0x4fb fp=0xc00cc0bf88 sp=0xc00cc0bdc8 pc=0x1793b1b
github.com/grafana/tempo/tempodb.(*readerWriter).compactionLoop(0xc0009c6840)
        /root/tempo/repo/tempo/tempodb/compactor.go:72 +0x77 fp=0xc00cc0bfc8 sp=0xc00cc0bf88 pc=0x17935d7
github.com/grafana/tempo/tempodb.(*readerWriter).EnableCompaction.func1()
        /root/tempo/repo/tempo/tempodb/tempodb.go:385 +0x26 fp=0xc00cc0bfe0 sp=0xc00cc0bfc8 pc=0x1799b26
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00cc0bfe8 sp=0xc00cc0bfe0 pc=0x46bac1
created by github.com/grafana/tempo/tempodb.(*readerWriter).EnableCompaction
        /root/tempo/repo/tempo/tempodb/tempodb.go:385 +0x1c5

```

**Comment by joe-elliott** [comment]
Thank you for the report! Some questions that might help us understand what's going on:

- Are you running one of our docker images or building the binary yourself?
- If you are building the binary can you share any details about how you are building it? Go version?
- Is this a distributed deployment or all in one?
- If this is a distributed deployment does it always occur in the compactor? or does it occur in other components as well?

**Comment by joe-elliott** [comment]
So we ingest 2M spans / 250MB/s in one of our internal clusters and have never seen this issue. However, I was just able to reproduce it in ~5 minutes by running our `./example/docker-compose/tempo-search` example. This leads me to believe that either this is triggered by specific traces that the synthetic load generator creates or this only occurs in the tempo all in one.

**Comment by altanozlu** [comment]
- We build our binary, i just use make tempo and go version is go1.18.2 linux/amd64
- it's all in one
- we use otel(otlp grpc) go,rust,python libraries and few go,rust otlp with jaeger exporter is also in use
- Our traces are mostly normal http calls, with 4-5 different services and few hundred spans. but sometimes go otel library produces calls with no root trace or it doesn't reach the tempo and a lot of different spans merge in there and it exceeds tempo limits idk why it happens.



here is our tempo config:
```
server:
  http_listen_port: 3200
  grpc_server_max_recv_msg_size: 14194304

querier:
  query_timeout: 120s
  search:
    query_timeout: 120s
distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
        thrift_http:                   #
        grpc:                          # for a production deployment you should only enable the receivers you need!
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
  search_tags_deny_list: ["http.target", "http.url", "net.host.ip", "http.user_agent", "test1", "http.request_content_length", "net.transport","params","otel.library.name"]
    #log_received_traces: true
ingester:
  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
  max_block_bytes: 1_000_000           # cut the head block when it hits this size or ...
  max_block_duration: 5m               #   this much time passes

compactor:
  compaction:
    compaction_window: 1h              # blocks in this time window will be compacted together
    max_block_bytes: 100_000_000       # maximum size of compacted blocks
    block_retention: 48h
    compacted_block_retention: 1h
metrics_generator_enabled: true
metrics_generator:
  registry:
    collection_interval: 1s
  processor:
    span_metrics:
      dimensions: ["http.status_code","messaging.destination","messaging.kafka.consumer_group"]
      histogram_buckets: [0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.02, 2.05, 4.10, 8.0, 10.5, 40]
  storage:
    path: tempo-data/mg/wal
    remote_write:
      - url: http://xxx:9090/api/v1/write
        send_exemplars: true
storage:
  trace:
    backend: local                     # backend configuration to use
    block:
      version: vParquet
      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
      #index_downsample_bytes: 1000     # number of bytes per index record
      encoding: zstd                   # block encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    wal:
      path: tempo-data/wal             # where to store the the wal locally
      encoding: snappy                 # wal encoding/compression.  options: none, gzip, lz4-64k, lz4-256k, lz4-1M, lz4, snappy, zstd, s2
    local:
      path: tempo-data/blocks
    pool:
      max_workers: 100                 # worker pool determines the number of parallel requests to the object store backend
      queue_depth: 10000
query_frontend:
  search:
    max_duration: 8h
overrides:
   metrics_generator_processors: [span-metrics] #[service-graphs, span-metrics]
   max_search_bytes_per_trace: 200000
   max_traces_per_user: 100000
```

**Comment by altanozlu** [comment]
hi it's crashed again, if u need full logs i can send to you via email.
```
runtime: marked free object in span 0x7f3859ec8280, elemsize=320 freeindex=3 (bad use of unsafe.Pointer? try -d=checkptr)
0xc000b40000 alloc unmarked
0xc000b40140 alloc marked
0xc000b40280 alloc marked
0xc000b403c0 alloc marked
0xc000b40500 alloc marked
0xc000b40640 free  marked   zombie
0x000000c000b40640:  0x69304e5f49435142  0x5263694336766871
0x000000c000b40650:  0x5764652d43626f4b  0x463342464d727064
0x000000c000b40660:  0x716d68375a764342  0x784549396c395651
0x000000c000b40670:  0x355a4e6668314137  0x546d443542353853
0x000000c000b40680:  0x383761537166536b  0x636d547831766e2d
0x000000c000b40690:  0x6662785f4154674c  0x325664544f743169
0x000000c000b406a0:  0x4f376a5431737251  0x7571754559676678
0x000000c000b406b0:  0x545451347336384b  0x4f59424e354d7752
0x000000c000b406c0:  0x4842336c5370374c  0x7a564f5858485130
0x000000c000b406d0:  0x3266305a6a6d6b58  0x417254726d50512d
0x000000c000b406e0:  0x46694b6a614c4930  0x6c4d54524e4b5846
0x000000c000b406f0:  0x6953507a7253312d  0x31726a557342725f
0x000000c000b40700:  0x534f356468664866  0x6b6d666446377971
0x000000c000b40710:  0x78347a625241314a  0x6a4f446153677056
0x000000c000b40720:  0x6b7053366d494969  0x5771446e72636e72
0x000000c000b40730:  0x7032684b49477647  0x64472d486b6c3439
0x000000c000b40740:  0x326779744d4c786e  0x6a525831464a6858
0x000000c000b40750:  0x71302d69584c4956  0x7069586752753341
0x000000c000b40760:  0x636f524a77724966  0x6955392d7a4d4756
0x000000c000b40770:  0x4342757477764334  0x000000000063345a <google.golang.org/protobuf/internal/impl.legacyLoadEnumType+0x000000000000015a>
0xc000b40780 free  unmarked
0xc000b408c0 free  unmarked
0xc000b40a00 free  unmarked
0xc000b40b40 free  unmarked
0xc000b40c80 alloc marked
0xc000b40dc0 alloc marked
0xc000b40f00 free  unmarked
0xc000b41040 alloc marked
0xc000b41180 free  unmarked
0xc000b412c0 free  unmarked
0xc000b41400 free  unmarked
0xc000b41540 free  unmarked
0xc000b41680 free  unmarked
0xc000b417c0 free  unmarked
0xc000b41900 free  unmarked
0xc000b41a40 free  unmarked
0xc000b41b80 free  unmarked
0xc000b41cc0 free  unmarked
0xc000b41e00 alloc marked
fatal error: found pointer to free object

runtime stack:
runtime.throw({0x1ffd4d0?, 0xc000b40780?})
        /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.(*mspan).reportZombies(0x7f3859ec8280)
        /usr/local/go/src/runtime/mgcsweep.go:776 +0x2e5
runtime.(*sweepLocked).sweep(0x100000000000000?, 0x0)
        /usr/local/go/src/runtime/mgcsweep.go:604 +0x338
runtime.(*mcentral).uncacheSpan(0xc000062000?, 0x7f3859c15db8?)
        /usr/local/go/src/runtime/mcentral.go:226 +0xa9
runtime.(*mcache).releaseAll(0x7f3880e88688)
        /usr/local/go/src/runtime/mcache.go:259 +0x125
runtime.(*mcache).prepareForSweep(0x7f3880e88688)
        /usr/local/go/src/runtime/mcache.go:295 +0x39
runtime.gcMarkTermination.func4.1(0xc0068ddfb8?)
        /usr/local/go/src/runtime/mgc.go:1057 +0x1d
runtime.forEachP(0x2098018)
        /usr/local/go/src/runtime/proc.go:1603 +0x11a
runtime.gcMarkTermination.func4()
        /usr/local/go/src/runtime/mgc.go:1056 +0x25
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:469 +0x49

goroutine 10 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc0000bdd40 sp=0xc0000bdd38 pc=0x4699e0
runtime.gcMarkTermination(0x3595020?)
        /usr/local/go/src/runtime/mgc.go:1055 +0x565 fp=0xc0000bdef8 sp=0xc0000bdd40 pc=0x41d2a5
runtime.gcMarkDone()
        /usr/local/go/src/runtime/mgc.go:904 +0x294 fp=0xc0000bdf58 sp=0xc0000bdef8 pc=0x41ca94
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1331 +0x2c5 fp=0xc0000bdfe0 sp=0xc0000bdf58 pc=0x41dd85
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000bdfe8 sp=0xc0000bdfe0 pc=0x46bac1
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1131 +0x25

goroutine 1 [select, 40 minutes]:
github.com/grafana/dskit/services.(*Manager).AwaitStopped(0xc00068ed80, {0x24e8318, 0xc0000500a0})
        /root/tempo/repo/tempo/vendor/github.com/grafana/dskit/services/manager.go:145 +0x6d
github.com/grafana/tempo/cmd/tempo/app.(*App).Run(0xc000950000)
        /root/tempo/repo/tempo/cmd/tempo/app/app.go:201 +0x868
main.main()
        /root/tempo/repo/tempo/cmd/tempo/main.go:108 +0x890

goroutine 307 [select, 40 minutes]:
github.com/grafana/tempo/modules/querier.(*Querier).running(0xc0002b4540, {0x24e82e0?, 0xc001298540?})
        /root/tempo/repo/tempo/modules/querier/querier.go:161 +0xa8
github.com/grafana/dskit/services.(*BasicService).main(0xc000844e60)
        /root/tempo/repo/tempo/vendor/github.com/grafana/dskit/services/basic_service.go:190 +0x1e8
created by github.com/grafana/dskit/services.(*BasicService).StartAsync.func1
        /root/tempo/repo/tempo/vendor/github.com/grafana/dskit/services/basic_service.go:119 +0x105

goroutine 55 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000298380)
        /root/tempo/repo/tempo/vendor/go.opencensus.io/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
        /root/tempo/repo/tempo/vendor/go.opencensus.io/stats/view/worker.go:34 +0x8d
```

**Comment by joe-elliott** [comment]
Thanks for the additional information. We believe this is isolated to the single binary because we still haven't seen this in our distributed deployments. However it can be reproduced fairly easily by simply starting up the `./example/docker-compose/tempo-search` and waiting.

Likely this is a conflict in the unsafe buffers used by the segmentio parquet library. We will work with them on reproducing/fixing the issue.

**Comment by altanozlu** [comment]
hi! also there is another error, when i restart tempo after crash, prometheus doesn't accept metrics for a while (5 to 30 minutes).
both prometheus and tempo in same server.
i checked prometheus and here is the log:
```
ts=2022-08-03T04:50:03.404Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=456
ts=2022-08-03T04:50:03.408Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=425
ts=2022-08-03T04:50:03.412Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=410
ts=2022-08-03T04:50:03.416Z caller=write_handler.go:122 level=warn component=web msg="Error on ingesting out-of-order exemplars" num_dropped=302
```

**Comment by altanozlu** [comment]
hi @joe-elliott, idk if it's luck or smth but we didn't get any crash for 3 days after using latest commits.

**Comment by joe-elliott** [comment]
That's odd, but also good news :)

This is the only PR in the last week or so that seems like it may have impacted it the issue. cc @mdisibio 
https://github.com/grafana/tempo/pull/1608

**Comment by joe-elliott** [comment]
I was able to repro this again this morning using the same docker-compose example mentioned above. However, it did take considerably longer. Attaching the dump here:

[dump.txt](https://github.com/grafana/tempo/files/9291053/dump.txt)

**Comment by altanozlu** [comment]
@joe-elliott after upgrading to latest tempo it started to crash again so i've reverted.

**Comment by joe-elliott** [comment]
Is the crash the same? Any additional info you can share? We have seen this fixed since:

https://github.com/grafana/tempo/commit/fb5f3667a45c1302735e40942fc99c087ee6cd02

**Comment by altanozlu** [comment]
it seems like crash is similar, it was ok for 7 hours, then i've restarted, removed data folder and added two lines to config.
it may be a coincidence but idk.
```
overrides:
   ingestion_rate_limit_bytes: 31457280
   max_bytes_per_trace: 15728640
```
```
runtime: marked free object in span 0x7f5e5c66d5b0, elemsize=64 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc045ab8000 free  unmarked
0xc045ab8040 free  unmarked
0xc045ab8080 free  unmarked
0xc045ab80c0 free  unmarked
0xc045ab8100 free  unmarked
0xc045ab8140 free  unmarked
0xc045ab8180 free  unmarked
0xc045ab81c0 alloc marked
0xc045ab8200 alloc marked
0xc045ab8240 free  unmarked
0xc045ab8280 free  unmarked
0xc045ab82c0 free  unmarked
0xc045ab8300 free  unmarked
0xc045ab8340 alloc marked
0xc045ab8380 free  unmarked
0xc045ab83c0 free  unmarked
0xc045ab8400 free  unmarked
0xc045ab8440 free  unmarked
0xc045ab8480 free  unmarked
0xc045ab84c0 free  unmarked
0xc045ab8500 free  unmarked
0xc045ab8540 free  unmarked
0xc045ab8580 free  unmarked
0xc045ab85c0 free  unmarked
0xc045ab8600 free  unmarked
0xc045ab8640 free  unmarked
0xc045ab8680 free  unmarked
0xc045ab86c0 free  unmarked
0xc045ab8700 free  unmarked
0xc045ab8740 free  unmarked
0xc045ab8780 free  unmarked
0xc045ab87c0 free  unmarked
0xc045ab8800 alloc marked
0xc045ab8840 free  unmarked
0xc045ab8880 free  unmarked
0xc045ab88c0 free  unmarked
0xc045ab8900 alloc marked
0xc045ab8940 free  unmarked
0xc045ab8980 alloc marked
0xc045ab89c0 free  unmarked
0xc045ab8a00 free  unmarked
0xc045ab8a40 alloc marked
0xc045ab8a80 free  unmarked
0xc045ab8ac0 alloc marked
0xc045ab8b00 free  unmarked
0xc045ab8b40 free  unmarked
0xc045ab8b80 alloc marked
0xc045ab8bc0 alloc marked
0xc045ab8c00 free  unmarked
0xc045ab8c40 free  unmarked
0xc045ab8cc0 free  unmarked
0xc045ab8d00 alloc marked
0xc045ab8d40 free  unmarked
0xc045ab8d80 alloc marked
0xc045ab8dc0 free  unmarked
0xc045ab8e00 free  unmarked
0xc045ab8e40 free  unmarked
0xc045ab8e80 free  unmarked
0xc045ab8ec0 free  unmarked
0xc045ab8f00 alloc marked
0xc045ab8f40 alloc marked
0xc045ab8f80 free  marked   zombie
0x000000c045ab8f80:  0x206c6c6174656768  0x726573753a677375
0x000000c045ab8f90:  0x31623a617461645f  0x372d396134653861
0x000000c045ab8fa0:  0x633937342d393362  0x66632d343561392d
0x000000c045ab8fb0:  0x6338653335363938  0x0000000000006466
0xc045ab8fc0 alloc marked
0xc045ab9000 free  unmarked
0xc045ab9040 free  unmarked
0xc045ab9080 free  unmarked
0xc045ab90c0 free  unmarked
0xc045ab9100 alloc marked
0xc045ab9140 alloc marked
0xc045ab9180 free  unmarked
0xc045ab91c0 free  unmarked
0xc045ab9200 free  unmarked
0xc045ab9240 alloc marked
0xc045ab9280 free  unmarked
0xc045ab92c0 free  unmarked
0xc045ab9300 free  unmarked
0xc045ab9340 free  unmarked
0xc045ab9380 free  unmarked
0xc045ab93c0 free  unmarked
0xc045ab9400 free  unmarked
0xc045ab9440 free  unmarked
0xc045ab9480 free  unmarked
0xc045ab94c0 free  unmarked
0xc045ab9500 alloc marked
0xc045ab9540 free  unmarked
0xc045ab9580 free  unmarked
0xc045ab95c0 free  unmarked
0xc045ab9600 free  unmarked
0xc045ab9640 alloc marked
0xc045ab9680 free  unmarked
0xc045ab96c0 free  unmarked
0xc045ab9700 free  unmarked
0xc045ab9740 free  unmarked
0xc045ab9780 free  unmarked
0xc045ab97c0 alloc marked
0xc045ab9800 alloc marked
0xc045ab9840 free  unmarked
0xc045ab9880 free  unmarked
0xc045ab98c0 free  unmarked
0xc045ab9900 alloc marked
0xc045ab9940 free  unmarked
0xc045ab9980 free  unmarked
0xc045ab99c0 free  unmarked
0xc045ab9a00 free  unmarked
0xc045ab9a40 free  unmarked
0xc045ab9a80 free  unmarked
0xc045ab9ac0 free  unmarked
0xc045ab9b00 free  unmarked
0xc045ab9b40 alloc marked
0xc045ab9b80 alloc marked
0xc045ab9bc0 alloc marked
0xc045ab9c00 free  unmarked
0xc045ab9c40 alloc marked
0xc045ab9c80 free  unmarked
0xc045ab9cc0 free  unmarked
0xc045ab9d00 free  unmarked
0xc045ab9d40 free  unmarked
0xc045ab9d80 alloc marked
0xc045ab9dc0 alloc marked
0xc045ab9e00 alloc marked
0xc045ab9e40 free  unmarked
0xc045ab9e80 alloc marked
0xc045ab9ec0 free  unmarked
0xc045ab9f00 alloc marked
0xc045ab9f40 free  unmarked
0xc045ab9f80 alloc marked
0xc045ab9fc0 alloc marked
fatal error: found pointer to free object

goroutine 3 [running]:
runtime.throw({0x206d4b2?, 0xc045ab8fc0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000bd5e8 sp=0xc0000bd5b8 pc=0x43a0fd
runtime.(*mspan).reportZombies(0x7f5e5c66d5b0)
        /usr/local/go/src/runtime/mgcsweep.go:787 +0x2e5 fp=0xc0000bd668 sp=0xc0000bd5e8 pc=0x4285c5
runtime.(*sweepLocked).sweep(0x3651ac0?, 0x0)
        /usr/local/go/src/runtime/mgcsweep.go:611 +0x8d2 fp=0xc0000bd740 sp=0xc0000bd668 pc=0x427fd2
runtime.sweepone()
        /usr/local/go/src/runtime/mgcsweep.go:369 +0xf4 fp=0xc0000bd790 sp=0xc0000bd740 pc=0x427434
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:281 +0x105 fp=0xc0000bd7c8 sp=0xc0000bd790 pc=0x4271e5
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000bd7e0 sp=0xc0000bd7c8 pc=0x41be06
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000bd7e8 sp=0xc0000bd7e0 pc=0x46e641
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b
```

**Comment by altanozlu** [comment]
Also sometimes in metrics it says there is 1m req/s in some routes idk if it's related.
deleting data fixes it.

**Comment by joe-elliott** [comment]
A couple of questions to help:

Do the crashes still seem to occur during compaction? 
What commit was stable and what commit brought the issue back?

**Comment by altanozlu** [comment]
mm idk how to check if it's happening during compaction, i have full log about 76mb if you want i can send it.
e0e47ad1bd33d3cad7166b7ff064c3c25c40d034 is stable now and probably buggy code was in 8c93f8b19f0ec1b35e1951e932643f18dead1299 because i've fetched the main
