### ISSUE TITLE
[TraceQL] Arithmetic Operators panic ingesters

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2015]
**Describe the bug**
Executing a query with arithmetic operators such as :
`{ span.http.status_code > ( 200 + 1 ) }`

panics ingesters with:

```
panic: operator + is not yet implemented

goroutine 104720405 [running]:
github.com/grafana/tempo/pkg/traceql.BinaryOperation.execute({0x1, {0x276fed0, 0xc07a5d1f00}, {0x276fed0, 0xc07a5d1f40}}, {{0xc0c63469e0, 0x8, 0x8}, 0x173d59baf87037a1, 0x173d59bba9c21e69, ...})
	/Users/marty/src/tempo/pkg/traceql/ast_execute.go:193 +0x122d
github.com/grafana/tempo/pkg/traceql.BinaryOperation.execute({0xa, {0x276fe30, 0xc066427320}, {0x276fe80, 0xc066427350}}, {{0xc0c63469e0, 0x8, 0x8}, 0x173d59baf87037a1, 0x173d59bba9c21e69, ...})
	/Users/marty/src/tempo/pkg/traceql/ast_execute.go:143 +0x207
github.com/grafana/tempo/pkg/traceql.SpansetFilter.evaluate({{0x276fe80?, 0xc066427380?}}, {0xc06afb0160?, 0x1, 0xb0?})
	/Users/marty/src/tempo/pkg/traceql/ast.go:269 +0x38a
github.com/grafana/tempo/pkg/traceql.Pipeline.evaluate({{0xc0643e1a90?, 0x2762228?, 0xc0664272f0?}}, {0xc06afb0160?, 0x173d59e03812e000?, 0xc0664236d0?})
	/Users/marty/src/tempo/pkg/traceql/ast.go:91 +0x82
github.com/grafana/tempo/pkg/traceql.(*Engine).Execute(0x2762180?, {0x2762228?, 0xc0664272c0?}, 0xc066426fc0, {0x274eee0, 0xc0c9c08360})
	/Users/marty/src/tempo/pkg/traceql/engine.go:65 +0x50c
github.com/grafana/tempo/modules/ingester.(*instance).searchWAL.func2({0x27781d0, 0xc077a6e580})
	/Users/marty/src/tempo/modules/ingester/instance_search.go:179 +0x3a7
created by github.com/grafana/tempo/modules/ingester.(*instance).searchWAL
	/Users/marty/src/tempo/modules/ingester/instance_search.go:215 +0x4c5
 ```

**Comment by joe-elliott** [comment]
Fixed in #2019
