### ISSUE TITLE
Crash in segmentio/parquet-go when reading block

### ISSUE THREAD

**Issue by gebn** [grafana/tempo#2690]
Hi folks, we have a singleton compactor which is unable to make progress due to a panic. Please let me know what further info I can provide. Ideally the compactor would repair this block, or at least log and ignore it.

**Environment:**
 - Infrastructure: Kubernetes, microservices
 - Version: `latest` Docker image, `283f2328c`

**Additional Context**

```
level=info ts=2023-07-24T17:56:20.655020952Z caller=main.go:221 msg="initialising OpenTracing tracer"
level=info ts=2023-07-24T17:56:20.656556079Z caller=main.go:108 msg="Starting Tempo" version="(version=2.2.0-rc.0, branch=main, revision=283f2328c)"
level=info ts=2023-07-24T17:56:20.830501783Z caller=server.go:354 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-07-24T17:56:20.831708877Z caller=memberlist_client.go:437 msg="Using memberlist cluster label and node name" cluster_label= node=compactor-6b5958d695-76qwf
ts=2023-07-24T17:56:20.831839736Z caller=memberlist_logger.go:74 level=warn msg="Binding to public address without encryption!"
level=info ts=2023-07-24T17:56:20.831893999Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=1 to_join=2
level=info ts=2023-07-24T17:56:20.832502215Z caller=module_service.go:82 msg=initialising module=internal-server
level=info ts=2023-07-24T17:56:20.832584522Z caller=module_service.go:82 msg=initialising module=store
level=info ts=2023-07-24T17:56:20.832607746Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2023-07-24T17:56:20.83328351Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2023-07-24T17:56:20.833331421Z caller=module_service.go:82 msg=initialising module=overrides
level=info ts=2023-07-24T17:56:20.833355076Z caller=module_service.go:82 msg=initialising module=compactor
ts=2023-07-24T17:56:20.840366621Z caller=memberlist_logger.go:74 level=warn msg="Refuting a suspect message (from: compactor-6b5958d695-76qwf)"
level=info ts=2023-07-24T17:56:20.850736448Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=7 elapsed_time=18.844212ms
level=info ts=2023-07-24T17:56:20.850768509Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=gossip:7946
level=info ts=2023-07-24T17:56:20.851033994Z caller=basic_lifecycler.go:259 msg="instance found in the ring" instance=compactor-6b5958d695-76qwf ring=compactor state=ACTIVE tokens=512 registered_at="2023-07-24 17:43:00 +0000 UTC"
level=info ts=2023-07-24T17:56:20.851450746Z caller=compactor.go:128 msg="waiting until compactor is ACTIVE in the ring"
level=info ts=2023-07-24T17:56:20.851481063Z caller=compactor.go:134 msg="compactor is ACTIVE in the ring"
level=info ts=2023-07-24T17:56:20.851488467Z caller=compactor.go:143 msg="waiting until compactor ring topology is stable" min_waiting=1m0s max_waiting=5m0s
level=info ts=2023-07-24T17:56:20.860543937Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=7 elapsed_time=9.775738ms
level=info ts=2023-07-24T17:57:20.851726759Z caller=compactor.go:147 msg="compactor ring topology is stable"
level=info ts=2023-07-24T17:57:20.851761756Z caller=tempodb.go:428 msg="polling enabled" interval=5m0s concurrency=50
level=info ts=2023-07-24T17:57:26.698242981Z caller=poller.go:217 msg="writing tenant index" tenant=single-tenant metas=700 compactedMetas=79
level=info ts=2023-07-24T17:57:26.792493075Z caller=poller.go:130 msg="blocklist poll complete" seconds=5.940715991
level=info ts=2023-07-24T17:57:26.79253247Z caller=compactor.go:160 msg="enabling compaction"
level=info ts=2023-07-24T17:57:26.792541307Z caller=tempodb.go:400 msg="compaction and retention enabled."
level=info ts=2023-07-24T17:57:26.792567406Z caller=app.go:196 msg="Tempo started"
level=info ts=2023-07-24T17:57:56.794669774Z caller=compactor.go:141 msg="Compacting hash" hashString=single-tenant-1-469505
level=info ts=2023-07-24T17:57:56.794739767Z caller=compactor.go:172 msg="beginning compaction" traceID=2b2adc78966a76d6
level=info ts=2023-07-24T17:57:56.794817304Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:0b8958c5-da36-4983-a4f1-cfa5fd33c947 MinID:[53 103 6 215 126 78 204 112 129 219 22 71 204 214 95 138] MaxID:[255 254 249 189 193 35 196 244 160 59 205 51 7 137 168 137] TenantID:single-tenant StartTime:2023-07-24 17:43:15 +0000 UTC EndTime:2023-07-24 17:52:51 +0000 UTC TotalObjects:142352 Size:56655092 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:2 FooterSize:13878}"
level=info ts=2023-07-24T17:57:56.814591924Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:59a69c80-6ddc-4851-8b7c-b0413a293f0b MinID:[71 46 187 85 61 4 201 187 55 165 38 129 128 105 14 253] MaxID:[255 255 231 9 214 199 97 186 159 18 122 168 112 15 36 157] TenantID:single-tenant StartTime:2023-07-24 17:33:20 +0000 UTC EndTime:2023-07-24 17:47:48 +0000 UTC TotalObjects:197578 Size:86380492 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:3 FooterSize:10622}"
level=info ts=2023-07-24T17:58:16.694032834Z caller=compactor.go:253 msg="wrote compacted block" meta="&{Version:vParquet2 BlockID:8f8b15d0-8cb9-4340-822e-fead1bd7b2f3 MinID:[72 0 0 0 73 0 0 0 74 0 0 0 75 0 0 0] MaxID:[255 255 231 9 214 199 97 186 159 18 122 168 112 15 36 157] TenantID:single-tenant StartTime:2023-07-24 17:33:20 +0000 UTC EndTime:2023-07-24 17:52:51 +0000 UTC TotalObjects:339732 Size:142470169 CompactionLevel:2 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:4 FooterSize:12006}"
level=info ts=2023-07-24T17:58:16.895252811Z caller=compactor.go:254 msg="compaction complete" elapsed=20.100472928s block="&{Version:vParquet2 BlockID:8f8b15d0-8cb9-4340-822e-fead1bd7b2f3 MinID:[72 0 0 0 73 0 0 0 74 0 0 0 75 0 0 0] MaxID:[255 255 231 9 214 199 97 186 159 18 122 168 112 15 36 157] TenantID:single-tenant StartTime:2023-07-24 17:33:20 +0000 UTC EndTime:2023-07-24 17:52:51 +0000 UTC TotalObjects:339732 Size:142470169 CompactionLevel:2 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:4 FooterSize:12006}"
level=info ts=2023-07-24T17:58:16.895301203Z caller=compactor.go:141 msg="Compacting hash" hashString=single-tenant-1-469500
level=info ts=2023-07-24T17:58:16.895320049Z caller=compactor.go:172 msg="beginning compaction" traceID=25c93b2e5364ae6f
level=info ts=2023-07-24T17:58:16.895338073Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:6b9b123d-d37f-4424-a085-9f13551cc95e MinID:[0 0 0 0 0 0 0 0 250 211 60 178 167 117 182 208] MaxID:[255 252 217 137 251 6 2 198 100 91 17 104 133 46 64 226] TenantID:single-tenant StartTime:2023-07-24 12:47:51 +0000 UTC EndTime:2023-07-24 12:59:18 +0000 UTC TotalObjects:352113 Size:815365006 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:5 FooterSize:27407}"
level=info ts=2023-07-24T17:58:16.914648811Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:a6a88987-4679-4650-889d-4435c0393d34 MinID:[1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0] MaxID:[255 253 101 201 59 188 18 208 172 101 196 96 78 212 58 109] TenantID:single-tenant StartTime:2023-07-24 12:42:28 +0000 UTC EndTime:2023-07-24 12:57:59 +0000 UTC TotalObjects:422331 Size:980692473 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:5 FooterSize:25480}"
panic: runtime error: slice bounds out of range [:-2041210597]

goroutine 3014 [running]:
github.com/segmentio/parquet-go.(*bufferPool).get(0x3cea040?, 0xffffffff8655991b?)
        /drone/src/vendor/github.com/segmentio/parquet-go/buffer.go:364 +0x13a
github.com/segmentio/parquet-go.(*Column).decompress(0xc000a3fba0, {0xc10c340000, 0x2cacaf83, 0x33f506e3}, 0x21a3158?)
        /drone/src/vendor/github.com/segmentio/parquet-go/column.go:515 +0x3e
github.com/segmentio/parquet-go.(*Column).decodeDictionary(0xc000a3fba0, {0x1fc6f60?}, 0x16b2886?, 0x21a3288?)
        /drone/src/vendor/github.com/segmentio/parquet-go/column.go:744 +0xfb
github.com/segmentio/parquet-go.(*filePages).readDictionaryPage(0xc000b68280, 0xc00600fbc0?, 0xc00600fbc0?)
        /drone/src/vendor/github.com/segmentio/parquet-go/file.go:615 +0x3f
github.com/segmentio/parquet-go.(*filePages).ReadPage(0xc000b68280)
        /drone/src/vendor/github.com/segmentio/parquet-go/file.go:550 +0x205
github.com/segmentio/parquet-go.(*rowGroupRows).ReadRows(0xc0005a0620, {0xc000bce000, 0x1, 0x1})
        /drone/src/vendor/github.com/segmentio/parquet-go/row_group.go:336 +0x302
github.com/segmentio/parquet-go.(*reader).ReadRows(0xc000af5960, {0xc000bce000?, 0x1?, 0x1?})
        /drone/src/vendor/github.com/segmentio/parquet-go/reader.go:325 +0xc2
github.com/segmentio/parquet-go.(*Reader).ReadRows(0xc000af5950, {0xc000bce000, 0x1, 0x1})
        /drone/src/vendor/github.com/segmentio/parquet-go/reader.go:242 +0x75
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*rawIterator).Next(0xc0011dcbd0, {0x40e12a, 0xc00600ef60})
        /drone/src/tempodb/encoding/vparquet2/block_iterator.go:65 +0xc9
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*bookmark[...]).current(0xc0021a3628, {0x2a370a8?, 0xc000ed2330?})
        /drone/src/tempodb/encoding/vparquet2/multiblock_iterator.go:145 +0x64
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*bookmark[...]).done(0x2a3e520, {0x2a370a8, 0xc000ed2330})
        /drone/src/tempodb/encoding/vparquet2/multiblock_iterator.go:155 +0xb0
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*MultiBlockIterator[...]).done(...)
        /drone/src/tempodb/encoding/vparquet2/multiblock_iterator.go:99
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*MultiBlockIterator[...]).Next(0x2a511e0, {0x2a370a8, 0xc000ed2330})
        /drone/src/tempodb/encoding/vparquet2/multiblock_iterator.go:33 +0xcc
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*Compactor).Compact(0xc0009c85a0, {0x2a370a8, 0xc000ed2330}, {0x2a1e240, 0xc0007271d0}, {0x2a47420, 0xc000c04bb0}, 0xc00075b7d0, {0xc00075ac40, 0x2, ...})
        /drone/src/tempodb/encoding/vparquet2/compactor.go:137 +0x825
github.com/grafana/tempo/tempodb.(*readerWriter).compact(0xc000b8bd40, {0x2a37000, 0xc000727630}, {0xc00075ac40?, 0x2, 0x2}, {0xc000f130b0, 0xd})
        /drone/src/tempodb/compactor.go:233 +0xa4f
github.com/grafana/tempo/tempodb.(*readerWriter).doCompaction(0xc000b8bd40, {0x2a37000, 0xc000727630})
        /drone/src/tempodb/compactor.go:143 +0x54c
github.com/grafana/tempo/tempodb.(*readerWriter).compactionLoop(0xc000b8bd40, {0x2a37000, 0xc000727630})
        /drone/src/tempodb/compactor.go:81 +0xd2
created by github.com/grafana/tempo/tempodb.(*readerWriter).EnableCompaction
        /drone/src/tempodb/tempodb.go:401 +0x30c
```

**Comment by joe-elliott** [comment]
This is possibly a corrupt block in your backend. Can you double check the two listed blocks right before the panic? See if there size is consistent with the meta.json?

You can also try loading them with a simple parquet CLI tool like:

https://github.com/stoewer/parquet-cli

**Comment by gebn** [comment]
Thanks for the super swift reply @joe-elliott! The `data.parquet` sizes are consistent with `meta.json`, however trying to open them indeed gives an `Invalid page header` error. Is the only option to delete these blocks?

I do think Tempo should do something other than get crash here. I suspect the trigger was an OOM. Somewhat separately, is there a section I've missed in the docs about suggested memory requirements for the compactor? It seems to be OOMing with 24Gi memory - is there a way to get it to use more disk instead?

**Comment by joe-elliott** [comment]
> The data.parquet sizes are consistent with meta.json, however trying to open them indeed gives an Invalid page header error. Is the only option to delete these blocks?

I'd say it's the easiest option :). It might be possible to repair them, but you'd likely have to get deep into the parquet format and make some adjustments to the library itself to load the corrupt file.

>  I suspect the trigger was an OOM

Do you mean the trigger for writing the corrupt file was an OOM? That is definitely a possibility. Do you have corrupt files often?

> It seems to be OOMing with 24Gi memory - is there a way to get it to use more disk instead?

That's a very large amount of memory. Ours use 5-6GB and sometimes I think that's too much. The normal cause of inflated ingester/compactor memory is very large traces. Do you know if you're consuming a lot of traces over 50 or 100MB?

**Comment by gebn** [comment]
Ok thanks, deleted the offending blocks.

> Do you have corrupt files often?

Not often, however we had an issue with OOMing ingesters around the same time, so it correlated. The lesson seems to be to overprovision memory.

> Do you know if you're consuming a lot of traces over 50 or 100MB?

We're using the default `max_bytes_per_trace`, so there shouldn't be any traces over 5MB. I wouldn't be surprised if we saw the odd trace that large being generated, but it should be truncated/dropped at the ingester layer. Assuming pprof is enabled, I'll capture a heap dump if it happens again.

**Comment by joe-elliott** [comment]
Yes, it would be interesting to see a heap dump when it was consuming 26GB of memory. Also, you should consider setting `GOMEMLIMIT` on the compactors. Ours is set like this:

```
    Environment:
      GOMEMLIMIT:                        10GiB
```
```
    Limits:
      memory:  10Gi
```

Like I said ours only use 5-6GB, but this is a safety net. If a compactor does spike in memory usage it will slow the compaction cycle down and allocate more CPU resources to garbage collection, but this is preferred to OOMing for a long running process like compaction.

Keep an eye on your CPU if you add this config though. If you don't have a CPU limit the go runtime can consume a LOT of CPU to keep it under GOMEMLIMIT.

**Comment by gebn** [comment]
Thanks for your continued help, I'll give `GOMEMLIMIT` a go. Likely related to large traces, I've noticed these in the compactor log:

```
level=warn ts=2023-07-26T11:41:49.657362141Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=84d7879293f1c333 discarded_span_count=2072
level=warn ts=2023-07-26T11:43:26.850007861Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=3a885528ff9dd901 discarded_span_count=1899
level=warn ts=2023-07-26T11:43:31.978551097Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=490d19298959f28a discarded_span_count=3982
level=warn ts=2023-07-26T11:43:36.463801595Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=55cca663766c5d97 discarded_span_count=1226
level=warn ts=2023-07-26T11:44:01.809453218Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=84d7879293f1c333 discarded_span_count=2037
level=warn ts=2023-07-26T11:44:12.659189778Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=8c1d14e2ff817ced discarded_span_count=1899
level=warn ts=2023-07-26T11:44:54.470990897Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=ad0a168759d01d5c discarded_span_count=6435
level=warn ts=2023-07-26T11:44:55.35553644Z caller=compactor.go:248 msg="max size of trace exceeded" tenant=single-tenant traceId=b218842d31618edb discarded_span_count=5055
```

These aren't causing OOMs, is there possibly a bug here, given these traces are making it past the distributor's `max_bytes_per_trace` setting, which is identical to the compactor's?

Got another crash when writing a block just now, please let me know if this is at all interesting, or needs a separate issue:

```
level=info ts=2023-07-26T11:45:55.749485283Z caller=compactor.go:172 msg="beginning compaction" traceID=79235bb3b727d652
level=info ts=2023-07-26T11:45:55.749503267Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:0d4737c2-7f3b-4519-a81d-1507f41f5eb3 MinID:[14 44 93 171 86 30 88 27 197 124 154 212 151 184 249 24] MaxID:[255 251 58 71 174 76 53 232 175 161 214 77 102 9 153 40] TenantID:single-tenant StartTime:2023-07-26 07:18:21 +0000 UTC EndTime:2023-07-26 07:29:20 +0000 UTC TotalObjects:151122 Size:453836378 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:2 FooterSize:22836}"
level=info ts=2023-07-26T11:45:55.775001497Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:add86d10-abf0-4608-afce-c7280f865af4 MinID:[49 182 111 108 172 106 34 131 119 40 181 26 84 141 3 76] MaxID:[255 248 236 237 106 218 53 115 33 90 71 65 165 214 248 1] TenantID:single-tenant StartTime:2023-07-26 07:27:55 +0000 UTC EndTime:2023-07-26 07:39:34 +0000 UTC TotalObjects:157510 Size:498500429 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:2 FooterSize:20523}"
level=info ts=2023-07-26T11:45:55.799923074Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:08e3ff6e-c16e-4ca6-a1c7-91c8f7d20a68 MinID:[0 117 126 192 90 9 153 146 27 189 43 114 83 38 15 172] MaxID:[255 251 14 65 119 218 107 202 207 127 204 197 8 146 23 36] TenantID:single-tenant StartTime:2023-07-26 07:38:48 +0000 UTC EndTime:2023-07-26 07:55:10 +0000 UTC TotalObjects:236468 Size:605512419 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:3 FooterSize:22654}"
level=info ts=2023-07-26T11:45:55.803876681Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet2 BlockID:a8bd3497-b1bc-4569-b347-852669f9643c MinID:[65 0 0 0 23 2 0 0 1 0 0 0 3 0 0 0] MaxID:[255 255 177 51 122 169 5 100 226 40 198 159 26 12 164 247] TenantID:single-tenant StartTime:2023-07-26 07:07:36 +0000 UTC EndTime:2023-07-26 07:20:30 +0000 UTC TotalObjects:245894 Size:683193797 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:3 FooterSize:23775}"
level=info ts=2023-07-26T11:45:57.088132354Z caller=retention.go:97 msg="deleting block" blockID=baffed6c-0859-4de6-ba67-744293a17d98 tenantID=single-tenant
level=info ts=2023-07-26T11:45:57.442988761Z caller=retention.go:97 msg="deleting block" blockID=8e43d0f2-73db-4e9b-b181-2873afc6ad8b tenantID=single-tenant
level=info ts=2023-07-26T11:45:57.789702847Z caller=retention.go:97 msg="deleting block" blockID=066c9459-90a8-47ce-a4e5-ac69c5494757 tenantID=single-tenant
level=info ts=2023-07-26T11:45:58.39323615Z caller=retention.go:97 msg="deleting block" blockID=6e1e253d-34c6-4561-ad49-f269d2a6767d tenantID=single-tenant
level=info ts=2023-07-26T11:45:58.768454948Z caller=retention.go:97 msg="deleting block" blockID=66489939-f464-42e1-9172-69d21babfb50 tenantID=single-tenant
level=info ts=2023-07-26T11:45:58.959849515Z caller=retention.go:97 msg="deleting block" blockID=185f3788-d413-405e-bddd-85c3a56a14d5 tenantID=single-tenant
level=info ts=2023-07-26T11:45:59.236327959Z caller=retention.go:97 msg="deleting block" blockID=8fa6692e-ec37-496b-a52e-2019a2edaf6b tenantID=single-tenant
panic: runtime error: slice bounds out of range [4294962755:4444:]

goroutine 3528 [running]:
github.com/segmentio/parquet-go.(*byteArrayPage).index(...)
        /drone/src/vendor/github.com/segmentio/parquet-go/page.go:983
github.com/segmentio/parquet-go.(*byteArrayDictionary).lookupString(0x200ac40?, {0xc018132e04?, 0x202f680?, 0xc00418013c?}, {{0xc00ea72bc0?, 0x4bae000?, 0xc001060000?}})
        /drone/src/vendor/github.com/segmentio/parquet-go/dictionary_amd64.go:86 +0xfa
github.com/segmentio/parquet-go.(*byteArrayDictionary).Bounds(0xc00036bc00, {0xc01812c000, 0x7c27, 0xc9cc})
        /drone/src/vendor/github.com/segmentio/parquet-go/dictionary.go:764 +0x254
github.com/segmentio/parquet-go.(*indexedPage).Bounds(0xc004c71410)
        /drone/src/vendor/github.com/segmentio/parquet-go/dictionary.go:1283 +0x96
github.com/segmentio/parquet-go.(*repeatedPage).Bounds(0x1fc7fe0?)
        /drone/src/vendor/github.com/segmentio/parquet-go/page.go:420 +0x69
github.com/segmentio/parquet-go.(*writerColumn).recordPageStats(0xc000748c80, 0x167d7?, 0xc000f689c0, {0x2a50da0, 0xc0344db7c0})
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:1312 +0xdc
github.com/segmentio/parquet-go.(*writerColumn).writeDataPage(0xc000748c80, {0x2a50da0, 0xc0344db7c0})
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:1213 +0x6e5
github.com/segmentio/parquet-go.(*writerColumn).flush(0xc000748c80)
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:951 +0xb2
github.com/segmentio/parquet-go.(*writerColumn).writeRows(0xc000748c80, {0xc01e6b2000?, 0x1312d0?, 0xc00ea735f0?})
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:1084 +0xc5
github.com/segmentio/parquet-go.(*writer).WriteRows.func1(0xc00ea73730?, 0x179084b?)
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:716 +0x170
github.com/segmentio/parquet-go.(*writer).writeRows(0xc0005d98c0, 0x1, 0xc00ea73680)
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:758 +0xbb
github.com/segmentio/parquet-go.(*writer).WriteRows(0x10?, {0xc00ea73718?, 0x3?, 0x0?})
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:695 +0x58
github.com/segmentio/parquet-go.(*Writer).WriteRows(...)
        /drone/src/vendor/github.com/segmentio/parquet-go/writer.go:157
github.com/segmentio/parquet-go.(*GenericWriter[...]).WriteRows(0xc000fd5030?, {0xc00ea73718?, 0x2a52700?, 0xc00ea73730?})
        /drone/src/vendor/github.com/segmentio/parquet-go/writer_go18.go:176 +0x2b
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*streamingBlock).AddRaw(0xc0001c95e0, {0xc003760160, 0x10, 0x10}, {0xc009cda000?, 0x92, 0x2a42dd8?}, 0xc08bf0?, 0xc0?)
        /drone/src/tempodb/encoding/vparquet2/create.go:148 +0x85
github.com/grafana/tempo/tempodb/encoding/vparquet2.(*Compactor).Compact(0xc033f7f180, {0x2a38588, 0xc033ff70b0}, {0x2a1f700, 0xc00072d1d0}, {0x2a48940, 0xc000c08be0}, 0xc0340706f0, {0xc034026540, 0x4, ...})
        /drone/src/tempodb/encoding/vparquet2/compactor.go:174 +0xbca
github.com/grafana/tempo/tempodb.(*readerWriter).compact(0xc000bf8780, {0x2a384e0, 0xc00072d590}, {0xc034026540?, 0x4, 0x4}, {0xc000f579d0, 0xd})
        /drone/src/tempodb/compactor.go:233 +0xa4f
github.com/grafana/tempo/tempodb.(*readerWriter).doCompaction(0xc000bf8780, {0x2a384e0, 0xc00072d590})
        /drone/src/tempodb/compactor.go:143 +0x54c
github.com/grafana/tempo/tempodb.(*readerWriter).compactionLoop(0xc000bf8780, {0x2a384e0, 0xc00072d590})
        /drone/src/tempodb/compactor.go:81 +0xd2
created by github.com/grafana/tempo/tempodb.(*readerWriter).EnableCompaction
        /drone/src/tempodb/tempodb.go:401 +0x30c
```

**Comment by joe-elliott** [comment]
> These aren't causing OOMs, is there possibly a bug here, given these traces are making it past the distributor's max_bytes_per_trace setting, which is identical to the compactor's?

It's impossible to 100% enforce max trace size. If your max trace size is 5MB and the ingester receives 4.99MB of a trace it will happily flush it to a block. If, an hour later, you receive another 4.99 MB for the same trace the ingester will again happily flush it to a block. The ingester only tracks max traces sizes for the current block.

This is why we also attempt to enforce max trace size during compaction. But even that doesn't cover all cases! You can push 4.99MB of the same trace every few hours for your entire retention and it will slowly get larger and larger.

> Got another crash when writing a block just now, please let me know if this is at all interesting, or needs a separate issue:

I'm afraid you've found yourself a write pattern that panics the parquet library. I suppose the good news is that we're not seeing ingester panics? Just compactors? I'd love for you to able to share some data so we can debug why this is occurring, but completely understand if that's not possible. 

I suppose we can close this issue with "corrupt block" and open a new one with your write panic. We should reference this issue though to easily find history.

**Comment by joe-elliott** [comment]
So obviously we need to dig to understand the write pattern that is tripping this, but I do believe this is a call to wrap all queries in defer/recover. We need to protect the ingester in particular from panics on queries.

**Comment by gebn** [comment]
Makes sense re trace size - thank you for the explanation. For the write panic, I can confirm it's just the compactor. It's rather bad - 82 crashes in the last 8 hours. I'll create a new issue.
