### ISSUE TITLE
Tempo compactor panics

### ISSUE THREAD

**Issue by Utwo** [grafana/tempo#2804]
**Describe the bug**
Logs from the Tempo Compactor deployment
```
level=info ts=2023-08-18T04:17:04.664765238Z caller=main.go:221 msg="initialising OpenTracing tracer"
level=info ts=2023-08-18T04:17:04.675519082Z caller=main.go:108 msg="Starting Tempo" version="(version=2.2.0, branch=HEAD, revision=cce8df1b6)"
level=info ts=2023-08-18T04:17:04.833983105Z caller=server.go:354 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-08-18T04:17:04.95098045Z caller=memberlist_client.go:437 msg="Using memberlist cluster label and node name" cluster_label= node=tempo-compactor-f64647488-wnxbn-35c587d3
level=info ts=2023-08-18T04:17:04.951561279Z caller=module_service.go:82 msg=initialising module=store
level=info ts=2023-08-18T04:17:04.951639347Z caller=module_service.go:82 msg=initialising module=internal-server
level=info ts=2023-08-18T04:17:04.951690093Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2023-08-18T04:17:04.951750247Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2023-08-18T04:17:04.951825429Z caller=module_service.go:82 msg=initialising module=usage-report
level=info ts=2023-08-18T04:17:04.951780835Z caller=module_service.go:82 msg=initialising module=overrides
level=info ts=2023-08-18T04:17:04.952319834Z caller=module_service.go:82 msg=initialising module=compactor
level=info ts=2023-08-18T04:17:04.95333262Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=6 to_join=2
level=info ts=2023-08-18T04:17:04.955323527Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=2 elapsed_time=2.481234ms
level=info ts=2023-08-18T04:17:04.955358954Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=dns+tempo-gossip-ring:7946
level=info ts=2023-08-18T04:17:04.955397737Z caller=basic_lifecycler.go:259 msg="instance found in the ring" instance=tempo-compactor-f64647488-wnxbn ring=compactor state=ACTIVE tokens=512 registered_at="2023-08-17 15:54:37 +0000 UTC"
level=info ts=2023-08-18T04:17:04.955885259Z caller=compactor.go:128 msg="waiting until compactor is ACTIVE in the ring"
level=info ts=2023-08-18T04:17:04.955929082Z caller=compactor.go:134 msg="compactor is ACTIVE in the ring"
level=info ts=2023-08-18T04:17:04.955946646Z caller=compactor.go:143 msg="waiting until compactor ring topology is stable" min_waiting=1m0s max_waiting=5m0s
level=info ts=2023-08-18T04:17:04.959695958Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=6 elapsed_time=4.337216ms
level=info ts=2023-08-18T04:18:04.956505015Z caller=compactor.go:147 msg="compactor ring topology is stable"
level=info ts=2023-08-18T04:18:04.956544831Z caller=tempodb.go:428 msg="polling enabled" interval=5m0s concurrency=50
level=info ts=2023-08-18T04:18:05.695585368Z caller=poller.go:217 msg="writing tenant index" tenant=single-tenant metas=69 compactedMetas=154
level=info ts=2023-08-18T04:18:05.764155309Z caller=poller.go:130 msg="blocklist poll complete" seconds=0.807589579
level=info ts=2023-08-18T04:18:05.764199423Z caller=compactor.go:160 msg="enabling compaction"
level=info ts=2023-08-18T04:18:05.764210524Z caller=tempodb.go:400 msg="compaction and retention enabled."
level=info ts=2023-08-18T04:18:05.764237795Z caller=app.go:196 msg="Tempo started"
level=info ts=2023-08-18T04:18:35.765290719Z caller=compactor.go:141 msg="Compacting hash" hashString=single-tenant-470049
level=info ts=2023-08-18T04:18:35.765332408Z caller=compactor.go:172 msg="beginning compaction" traceID=560f0f7301109e22
level=info ts=2023-08-18T04:18:35.765403933Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet BlockID:b2e0be16-196d-4dc5-ba0e-796a099f7f5b MinID:[0 6 10 136 238 243 72 252 220 178 0 140 193 203 143 66] MaxID:[255 215 0 89 155 166 216 176 217 219 98 200 244 95 184 12] TenantID:single-tenant StartTime:2023-08-16 09:53:08 +0000 UTC EndTime:2023-08-16 09:58:08 +0000 UTC TotalObjects:1463 Size:20753309 CompactionLevel:1 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:1 FooterSize:7437}"
level=info ts=2023-08-18T04:18:35.836454267Z caller=compactor.go:184 msg="compacting block" block="&{Version:vParquet BlockID:3920e603-5d2f-4e6e-8c43-39f5179d365e MinID:[0 1 100 56 108 125 13 248 255 152 47 0 241 198 118 225] MaxID:[255 254 149 229 39 190 219 107 145 48 87 242 205 2 206 17] TenantID:single-tenant StartTime:2023-08-16 09:10:56 +0000 UTC EndTime:2023-08-16 09:53:30 +0000 UTC TotalObjects:38839 Size:449143229 CompactionLevel:3 Encoding:none IndexPageSize:0 TotalRecords:1 DataEncoding: BloomShardCount:1 FooterSize:7820}"
panic: runtime error: slice bounds out of range [:-1191509674]

goroutine 2195 [running]:
github.com/segmentio/parquet-go.(*bufferPool).get(0x3cea040?, 0xffffffffb8fb0156?)
	/drone/src/vendor/github.com/segmentio/parquet-go/buffer.go:364 +0x13a
github.com/segmentio/parquet-go.(*Column).decompress(0xc044b11e10, {0xc058e70000, 0x19ed9b47, 0x22a359ed}, 0x41551140?)
	/drone/src/vendor/github.com/segmentio/parquet-go/column.go:515 +0x3e
github.com/segmentio/parquet-go.(*Column).decodeDictionary(0xc044b11e10, {0x1fc6f20?}, 0x16b28a6?, 0x41551270?)
	/drone/src/vendor/github.com/segmentio/parquet-go/column.go:744 +0xfb
github.com/segmentio/parquet-go.(*filePages).readDictionaryPage(0xc00093bd60, 0xc044b5c330?, 0xc044b5c330?)
	/drone/src/vendor/github.com/segmentio/parquet-go/file.go:615 +0x3f
github.com/segmentio/parquet-go.(*filePages).ReadPage(0xc00093bd60)
	/drone/src/vendor/github.com/segmentio/parquet-go/file.go:550 +0x205
github.com/segmentio/parquet-go.(*rowGroupRows).ReadRows(0xc0429f42a0, {0xc0006d0048, 0x1, 0x1})
	/drone/src/vendor/github.com/segmentio/parquet-go/row_group.go:336 +0x302
github.com/segmentio/parquet-go.(*reader).ReadRows(0xc04348ba80, {0xc0006d0048?, 0x1?, 0x1?})
	/drone/src/vendor/github.com/segmentio/parquet-go/reader.go:325 +0xc2
github.com/segmentio/parquet-go.(*Reader).ReadRows(0xc04348ba70, {0xc0006d0048, 0x1, 0x1})
	/drone/src/vendor/github.com/segmentio/parquet-go/reader.go:242 +0x75
github.com/grafana/tempo/tempodb/encoding/vparquet.(*rawIterator).Next(0xc044279860, {0x0, 0xc041551618})
	/drone/src/tempodb/encoding/vparquet/block_iterator.go:65 +0xc9
github.com/grafana/tempo/tempodb/encoding/vparquet.(*bookmark[...]).current(0xc041551601, {0x2a370e8?, 0xc04424c540?})
	/drone/src/tempodb/encoding/vparquet/multiblock_iterator.go:145 +0x64
github.com/grafana/tempo/tempodb/encoding/vparquet.(*bookmark[...]).peekID(0x2a3e500, {0x2a370e8, 0xc04424c540})
	/drone/src/tempodb/encoding/vparquet/multiblock_iterator.go:132 +0xbd
github.com/grafana/tempo/tempodb/encoding/vparquet.(*MultiBlockIterator[...]).Next(0x2a51180, {0x2a370e8, 0xc04424c540})
	/drone/src/tempodb/encoding/vparquet/multiblock_iterator.go:44 +0x1cc
github.com/grafana/tempo/tempodb/encoding/vparquet.(*Compactor).Compact(0xc04314ab40, {0x2a370e8, 0xc04424c540}, {0x2a1e280, 0xc0000c6d70}, {0x2a47460, 0xc04112acd0}, 0xc04410bfa0, {0xc04423aea0, 0x2, ...})
	/drone/src/tempodb/encoding/vparquet/compactor.go:137 +0x825
github.com/grafana/tempo/tempodb.(*readerWriter).compact(0xc041116900, {0x2a37040, 0xc00075e230}, {0xc04423aea0?, 0x2, 0x2}, {0xc04115d7b0, 0xd})
	/drone/src/tempodb/compactor.go:233 +0xa4f
github.com/grafana/tempo/tempodb.(*readerWriter).doCompaction(0xc041116900, {0x2a37040, 0xc00075e230})
	/drone/src/tempodb/compactor.go:143 +0x54c
github.com/grafana/tempo/tempodb.(*readerWriter).compactionLoop(0xc041116900, {0x2a37040, 0xc00075e230})
	/drone/src/tempodb/compactor.go:81 +0xd2
created by github.com/grafana/tempo/tempodb.(*readerWriter).EnableCompaction
	/drone/src/tempodb/tempodb.go:401 +0x30c
```

**To Reproduce**
1. Start Tempo using helm chart 1.5.0
2. Perform Operations (Read/Write/Others)

**Environment:**
 - Infrastructure: Kubernetes, k3s
 - Deployment tool: Helm

**Additional Context**
Previously the compactor crashed a couple of times because of OOM.

**Comment by joe-elliott** [comment]
> Previously the compactor crashed a couple of times because of OOM.

Likely you have a partially written/corrupt block as a result of the OOMs. I would advise removing the corrupt block. If it persists then we can dig deeper.

We should put this in a doc somewhere, but I'd recommend the following to help with compactor OOMs:

https://github.com/grafana/tempo/issues/2162#issuecomment-1453692842

**Comment by Utwo** [comment]
Thank you! It worked! I didn't realize that the id in the log is also available in the bucket.
