### ISSUE TITLE
Panic on distributor shutdown

### ISSUE THREAD

**Issue by chancez** [grafana/tempo#342]
**Describe the bug**
The tempo distributor panics on shutdown consistently

**To Reproduce**
1. Start Tempo 0.3.0
2. Roll out a new version (using tanka apply)
3. Distributor panics during shutdown:

```
2020-11-13T10:12:07-08:00 level=info ts=2020-11-13T18:12:07.596900857Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
2020-11-13T10:12:07-08:00 level=error ts=2020-11-13T18:12:07.59840847Z caller=shim.go:186 msg="fatal error reported" err="http: Server closed"
2020-11-13T10:12:07-08:00 panic: Fatal error http: Server closed
2020-11-13T10:12:07-08:00
2020-11-13T10:12:07-08:00 goroutine 283 [running]:
2020-11-13T10:12:07-08:00 github.com/grafana/tempo/modules/distributor/receiver.(*receiversShim).ReportFatalError(0xc000095140, 0x2c37bc0, 0xc000088ac0)
2020-11-13T10:12:07-08:00 /drone/src/modules/distributor/receiver/shim.go:187 +0x1f7
2020-11-13T10:12:07-08:00 go.opentelemetry.io/collector/receiver/otlpreceiver.(*Receiver).Start.func1.2(0xc000a53cc0, 0x2c929a0, 0xc00028a1e0, 0x2c9db60, 0xc000095140)
2020-11-13T10:12:07-08:00 /drone/src/vendor/go.opentelemetry.io/collector/receiver/otlpreceiver/otlp.go:103 +0x7c
2020-11-13T10:12:07-08:00 created by go.opentelemetry.io/collector/receiver/otlpreceiver.(*Receiver).Start.func1
2020-11-13T10:12:07-08:00 /drone/src/vendor/go.opentelemetry.io/collector/receiver/otlpreceiver/otlp.go:101 +0x126
```

**Expected behavior**
Distributor gracefully stops and does not panic.

**Environment:**
 - Infrastructure: Kubernetes/EKS
 - Deployment tool: tanka/jsonnet

**Comment by joe-elliott** [comment]
Thanks for reporting this.  This is just a misunderstanding on my part.  Filing a fix PR now.
