### ISSUE TITLE
Query-frontend will occasionally panic when under sustained load

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#843]
**Describe the bug**

Query-frontend will occasionally panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47ad05]
goroutine 302 [running]:
errors.(*errorString).Error(0x0, 0x209c7e0, 0x0)
	/usr/local/go/src/errors/errors.go:68 +0x5
github.com/opentracing/opentracing-go/log.Field.Marshal(0x2485b37, 0xc, 0x9, 0x0, 0x0, 0x0, 0x209c7e0, 0x0, 0x2995038, 0xc06a0b00d8)
	/drone/src/vendor/github.com/opentracing/opentracing-go/log/field.go:231 +0x309
github.com/uber/jaeger-client-go.ConvertLogsToJaegerTags(0xc000a68780, 0x3, 0x3, 0xc06984e008, 0x39c7248, 0xc000cfbd78)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_tag.go:31 +0x13f
github.com/uber/jaeger-client-go.buildLogs(0xc06975e480, 0x1, 0x1, 0x100, 0x39c7248, 0x0)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_thrift_span.go:82 +0x145
github.com/uber/jaeger-client-go.BuildJaegerThrift(0xc0697586c0, 0x0)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_thrift_span.go:43 +0x16c
github.com/uber/jaeger-client-go.(*udpSender).Append(0xc000ccad80, 0xc0697586c0, 0x0, 0x0, 0x2)
	/drone/src/vendor/github.com/uber/jaeger-client-go/transport_udp.go:129 +0x45
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc000533f80)
	/drone/src/vendor/github.com/uber/jaeger-client-go/reporter.go:304 +0x1c2
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/drone/src/vendor/github.com/uber/jaeger-client-go/reporter.go:237 +0x1a5
```

We observed this while receiving a constant load of about 23 queries per second.

**To Reproduce**
1. Run Tempo
2. Send a ton of queries

**Expected behavior**
Tempo should not panic.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Additional Context**

**Comment by kvrhdn** [comment]
Looking at when these panics started appearing, I believe this was introduced between 5ad92c9c and 3638caa. The only change in the query-frontend is the #814...

**Comment by kvrhdn** [comment]
Example of how you can cause this: https://play.golang.org/p/K4rrupMiAYt
```
package main

import (
	"fmt"
)

func main() {
	err := badError()

	// safe way to print
	fmt.Println(err)

	// nil check fails to catch this
	if err != nil {
		fmt.Println(err.Error()) // this still panics!
	}
}

func badError() error {
	var m *myErr
	return m
}

type myErr struct {
	s string
}

func (m *myErr) Error() string {
	return fmt.Sprintf("%s\n", m.s)
}
```

**Comment by kvrhdn** [comment]
Closing in favour of https://github.com/grafana/tempo/issues/857
