### ISSUE TITLE
Query-frontend panics during error handling

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#853]
**Describe the bug**
Similar to #843 (but less frequent): the query-frontend occasionally panics while serving a request. This only shows up when under constant load.

Stacktrace:
```
2021/08/04 03:21:46 http: panic serving 10.144.107.127:58606: runtime error: invalid memory address or nil pointer dereference
goroutine 20312516 [running]:
net/http.(*conn).serve.func1(0xc06fb79040)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x210d9e0, 0x398d2d0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1(0xc04cfb1ad0, 0x29b53c0, 0xc04c3f4c60)
	/drone/src/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:150 +0x1ab
panic(0x210d9e0, 0x398d2d0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
errors.(*errorString).Error(0x0, 0x11684306beaddd, 0xc042ded1a0)
	/usr/local/go/src/errors/errors.go:68 +0x5
github.com/cortexproject/cortex/pkg/util.IsRequestBodyTooLarge(0x294dca0, 0x0, 0xc00011e2a0)
	/drone/src/vendor/github.com/cortexproject/cortex/pkg/util/http.go:27 +0x46
github.com/cortexproject/cortex/pkg/frontend/transport.writeError(0x298ac50, 0xc04cfaf200, 0x294dca0, 0x0)
	/drone/src/vendor/github.com/cortexproject/cortex/pkg/frontend/transport/handler.go:213 +0x65
github.com/cortexproject/cortex/pkg/frontend/transport.(*Handler).ServeHTTP(0xc0000b6780, 0x298ac50, 0xc04cfaf200, 0xc04c3e1000)
	/drone/src/vendor/github.com/cortexproject/cortex/pkg/frontend/transport/handler.go:118 +0x8bd
github.com/weaveworks/common/middleware.glob..func1.1(0x298ac50, 0xc04cfaf200, 0xc04c3e0f00)
	/drone/src/vendor/github.com/weaveworks/common/middleware/http_auth.go:17 +0x147
net/http.HandlerFunc.ServeHTTP(0xc0002915a8, 0x298ac50, 0xc04cfaf200, 0xc04c3e0f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002f43c0, 0x298ac50, 0xc04cfaf200, 0xc04c3e0d00)
	/drone/src/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x298ac50, 0xc04cfaf200)
	/drone/src/vendor/github.com/weaveworks/common/middleware/instrument.go:68 +0x4c
github.com/felixge/httpsnoop.CaptureMetricsFn(0x2985eb0, 0xc04c3e7400, 0xc042ded790, 0x2, 0x29b1d70, 0xc0414f01c0)
	/drone/src/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b
github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2985eb0, 0xc04c3e7400, 0xc04c3e0d00)
	/drone/src/vendor/github.com/weaveworks/common/middleware/instrument.go:67 +0x325
net/http.HandlerFunc.ServeHTTP(0xc0000b6370, 0x2985eb0, 0xc04c3e7400, 0xc04c3e0d00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/weaveworks/common/middleware.Log.Wrap.func1(0x298ad70, 0xc04c3e73b0, 0xc04c3e0d00)
	/drone/src/vendor/github.com/weaveworks/common/middleware/logging.go:52 +0x1a9
net/http.HandlerFunc.ServeHTTP(0xc000930180, 0x298ad70, 0xc04c3e73b0, 0xc04c3e0d00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2989360, 0xc04c384b60, 0xc04c3e0c00)
	/drone/src/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4
net/http.HandlerFunc.ServeHTTP(0xc000930340, 0x2989360, 0xc04c384b60, 0xc04c3e0c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0002082a0, 0x2989360, 0xc04c384b60, 0xc04c3e0c00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc06fb79040, 0x2993da8, 0xc054f11a80)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**To Reproduce**
1. Run Tempo
2. Send a ton of queries

**Expected behavior**

Should not panic.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Jsonnet

**Additional Context**

**Comment by kvrhdn** [comment]
Some analysis:
- panic happens when [`IsRequestTooLarge` calls `err.Error()`](https://github.com/cortexproject/cortex/blob/4405f9c339779b5861f5755bd867ee7bac4f4fa9/pkg/util/http.go#L25-L28)
- `IsRequestTooLarge` is called by `writeError`, [which is called in `(*transport.Handler).ServeHTTP`](https://github.com/cortexproject/cortex/blob/4405f9c339779b5861f5755bd867ee7bac4f4fa9/pkg/frontend/transport/handler.go#L128-L134)

Conclusion the 'bad' error must have been returned by the roundtripper.

#843 also panicked when calling `err.Error()` on an error returned by the tripperware.

**Comment by kvrhdn** [comment]
Closing in favour of https://github.com/grafana/tempo/issues/857
