### ISSUE TITLE
Query-frontend: errors returned by frontend tripperware can panic when calling .Error()

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#857]
**Describe the bug**
This is combination of two issues: #843 and #853

We are seeing panics in the query-frontend while handling errors returned by the Cortex frontend tripperware. The panic happens because calling `err.Error()` causes a nil pointer dereference.
This happens both in Tempo code as well as in the vendored Cortex code.

**NOTE**: if you are experiencing this yourself, one way to lower how often this error triggers to disable the retry middleware in the query-frontend by setting `max_retries` to `0`. The retry middleware has to inspect every error and will trigger this panic more often. This will not completely solve this issue as other code can also trigger the panics occasionally.

Case 1: panic while logging the error using `ot_log.Error(err)`. More details: https://github.com/grafana/tempo/issues/843#issuecomment-890943569

<details>
<summary>Stacktrace</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47ad05]
goroutine 302 [running]:
errors.(*errorString).Error(0x0, 0x209c7e0, 0x0)
	/usr/local/go/src/errors/errors.go:68 +0x5
github.com/opentracing/opentracing-go/log.Field.Marshal(0x2485b37, 0xc, 0x9, 0x0, 0x0, 0x0, 0x209c7e0, 0x0, 0x2995038, 0xc06a0b00d8)
	/drone/src/vendor/github.com/opentracing/opentracing-go/log/field.go:231 +0x309
github.com/uber/jaeger-client-go.ConvertLogsToJaegerTags(0xc000a68780, 0x3, 0x3, 0xc06984e008, 0x39c7248, 0xc000cfbd78)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_tag.go:31 +0x13f
github.com/uber/jaeger-client-go.buildLogs(0xc06975e480, 0x1, 0x1, 0x100, 0x39c7248, 0x0)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_thrift_span.go:82 +0x145
github.com/uber/jaeger-client-go.BuildJaegerThrift(0xc0697586c0, 0x0)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_thrift_span.go:43 +0x16c
github.com/uber/jaeger-client-go.(*udpSender).Append(0xc000ccad80, 0xc0697586c0, 0x0, 0x0, 0x2)
	/drone/src/vendor/github.com/uber/jaeger-client-go/transport_udp.go:129 +0x45
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc000533f80)
	/drone/src/vendor/github.com/uber/jaeger-client-go/reporter.go:304 +0x1c2
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/drone/src/vendor/github.com/uber/jaeger-client-go/reporter.go:237 +0x1a5
```

</details>

Case 2: panic because Cortex inspects the error message. Some analysis: https://github.com/grafana/tempo/issues/853#issuecomment-892533491

<details>
<summary>Stacktrace</summary>

```
2021/08/04 03:21:46 http: panic serving 10.144.107.127:58606: runtime error: invalid memory address or nil pointer dereference
goroutine 20312516 [running]:
net/http.(*conn).serve.func1(0xc06fb79040)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x210d9e0, 0x398d2d0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1(0xc04cfb1ad0, 0x29b53c0, 0xc04c3f4c60)
	/drone/src/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:150 +0x1ab
panic(0x210d9e0, 0x398d2d0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
errors.(*errorString).Error(0x0, 0x11684306beaddd, 0xc042ded1a0)
	/usr/local/go/src/errors/errors.go:68 +0x5
github.com/cortexproject/cortex/pkg/util.IsRequestBodyTooLarge(0x294dca0, 0x0, 0xc00011e2a0)
	/drone/src/vendor/github.com/cortexproject/cortex/pkg/util/http.go:27 +0x46
github.com/cortexproject/cortex/pkg/frontend/transport.writeError(0x298ac50, 0xc04cfaf200, 0x294dca0, 0x0)
	/drone/src/vendor/github.com/cortexproject/cortex/pkg/frontend/transport/handler.go:213 +0x65
github.com/cortexproject/cortex/pkg/frontend/transport.(*Handler).ServeHTTP(0xc0000b6780, 0x298ac50, 0xc04cfaf200, 0xc04c3e1000)
	/drone/src/vendor/github.com/cortexproject/cortex/pkg/frontend/transport/handler.go:118 +0x8bd
github.com/weaveworks/common/middleware.glob..func1.1(0x298ac50, 0xc04cfaf200, 0xc04c3e0f00)
	/drone/src/vendor/github.com/weaveworks/common/middleware/http_auth.go:17 +0x147
net/http.HandlerFunc.ServeHTTP(0xc0002915a8, 0x298ac50, 0xc04cfaf200, 0xc04c3e0f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002f43c0, 0x298ac50, 0xc04cfaf200, 0xc04c3e0d00)
	/drone/src/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x298ac50, 0xc04cfaf200)
	/drone/src/vendor/github.com/weaveworks/common/middleware/instrument.go:68 +0x4c
github.com/felixge/httpsnoop.CaptureMetricsFn(0x2985eb0, 0xc04c3e7400, 0xc042ded790, 0x2, 0x29b1d70, 0xc0414f01c0)
	/drone/src/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b
github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2985eb0, 0xc04c3e7400, 0xc04c3e0d00)
	/drone/src/vendor/github.com/weaveworks/common/middleware/instrument.go:67 +0x325
net/http.HandlerFunc.ServeHTTP(0xc0000b6370, 0x2985eb0, 0xc04c3e7400, 0xc04c3e0d00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/weaveworks/common/middleware.Log.Wrap.func1(0x298ad70, 0xc04c3e73b0, 0xc04c3e0d00)
	/drone/src/vendor/github.com/weaveworks/common/middleware/logging.go:52 +0x1a9
net/http.HandlerFunc.ServeHTTP(0xc000930180, 0x298ad70, 0xc04c3e73b0, 0xc04c3e0d00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2989360, 0xc04c384b60, 0xc04c3e0c00)
	/drone/src/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4
net/http.HandlerFunc.ServeHTTP(0xc000930340, 0x2989360, 0xc04c384b60, 0xc04c3e0c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0002082a0, 0x2989360, 0xc04c384b60, 0xc04c3e0c00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc06fb79040, 0x2993da8, 0xc054f11a80)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

</details>

I can recreate a panicking `.Error()` implementation by returning a nil value as a non-nil interface.
[play.golang](https://play.golang.org/p/6lZr3lW3Jeg)

<details>
<summary>Code</summary>

```
package main

import (
	"fmt"
)

func main() {
	err := badError()

	// safe way to print
	fmt.Println(err)

	// nil check fails to catch this
	if err != nil {
		fmt.Println(err.Error()) // this still panics!
	}
}

func badError() error {
	var m *myErr
	return m // we are returning a nil value that implements error
}

type myErr struct {
	s string
}

func (m *myErr) Error() string {
	return fmt.Sprintf("%s\n", m.s)
}
```

</details>

But according to the stacktrace the panic happens in `errors.(*errorString).Error` which is part of stdlib... I am not able to reproduce this.

**To Reproduce**
1. Run Tempo (must probably be distributed)
2. Send a lot of queries
3. A small fraction of queries will fail with 500 because the query-frontend panics

**Expected behavior**
Tempo should never panic when handling queries.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Jsonnet

**Additional Context**

**Comment by joe-elliott** [comment]
Seeing a possible third case:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47ae45]
goroutine 88361 [running]:
errors.(*errorString).Error(0x0, 0x2a5fce0, 0x0)
    /usr/local/go/src/errors/errors.go:68 +0x5
github.com/gogo/status.FromError(0x2a5fce0, 0x0, 0x4a49dc, 0xc043668480)
    /drone/src/vendor/github.com/gogo/status/status.go:147 +0x7a
github.com/weaveworks/common/httpgrpc.HTTPResponseFromError(0x2a5fce0, 0x0, 0x0, 0x2a5fce0)
    /drone/src/vendor/github.com/weaveworks/common/httpgrpc/httpgrpc.go:38 +0x39
github.com/grafana/tempo/modules/frontend.retryWare.Do(0x2a61ac0, 0xc000194a20, 0x5, 0x2aad338, 0xc00057b830, 0xc043b7fb00, 0x0, 0x0, 0x0)
    /drone/src/modules/frontend/retry.go:60 +0x326
github.com/grafana/tempo/modules/frontend.doRequests.func1(0x2a67820, 0xc0008390b0, 0xc0000b9da0, 0xc0000b9d40, 0xc043b7fb00)
    /drone/src/modules/frontend/querysharding.go:125 +0x47
created by github.com/grafana/tempo/modules/frontend.doRequests
    /drone/src/modules/frontend/querysharding.go:124 +0xd3
```

**Comment by annanay25** [comment]
One duct-tape-solution is to use `reflect.ValueOf(err).IsNil()` - https://play.golang.org/p/faAIClD9RdD

But we may ofcourse want to drill deeper into Cortex code to understand
